//
//  SlidingInteractor.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SlidingBusinessLogic
{
  func doSomething(request: Sliding.Something.Request)
}

protocol SlidingDataStore
{
  //var name: String { get set }
}

class SlidingInteractor: SlidingBusinessLogic, SlidingDataStore
{
  var presenter: SlidingPresentationLogic?
  var worker: SlidingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Sliding.Something.Request)
  {
    worker = SlidingWorker()
    worker?.doSomeWork()
    
    let response = Sliding.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
