//
//  LoginPresenter.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func loginSuccess(response: Login.Success.Response)
    func loginFail(response: Login.Fail.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
    func loginSuccess(response: Login.Success.Response) {
        let viewModel = Login.Success.ViewModel(userId:response.userId)
        viewController?.loginSuccess(viewModel: viewModel)
    }
    
    func loginFail(response: Login.Fail.Response) {
        let viewModel = Login.Fail.ViewModel(message: response.message)
        viewController?.loginFail(viewModel: viewModel)
    }
}
