//
//  LoginModels.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Success
  {
    struct Request
    {
        var mobileNumber:String
    }
    struct Response
    {
        var userId:String
    }
    struct ViewModel
    {
        var userId:String
    }
  }
    
    enum Fail {
        struct Request {
            var mobileNumber:String
        }
        struct Response {
            var message:String
        }
        struct ViewModel {
            var message:String
        }
    }
}
