//
//  LoginInteractor.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func createLogin(request: Login.Success.Request)
}

protocol LoginDataStore
{
  var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  var name: String = ""
  
  // MARK: Do something
    
    func createLogin(request: Login.Success.Request) {
        let result = ServiceAPI.loginWith(request: request)
        if result == "123" {
            presenter?.loginSuccess(response: Login.Success.Response(userId: result))
        }
        else {
            presenter?.loginFail(response: Login.Fail.Response(message: result))
        }
    }
}


