//
//  VerifyInteractor.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyBusinessLogic
{
  func doSomething(request: Verify.Something.Request)
//    func verifySuccess(request: Verify.Something.Request)
}

protocol VerifyDataStore
{
  var name: String { get set }
}

class VerifyInteractor: VerifyBusinessLogic, VerifyDataStore
{
  var presenter: VerifyPresentationLogic?
  var worker: VerifyWorker?
  var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Verify.Something.Request)
  {
    worker = VerifyWorker()
    worker?.doSomeWork()
    
    let response = Verify.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
