//
//  VerifyViewController.swift
//  CleanSwiftSampleApp
//
//  Created by cloudZon Infosoft on 31/05/18.
//  Copyright (c) 2018 MB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyDisplayLogic: class
{
  func displaySomething(viewModel: Verify.Something.ViewModel)
}

class VerifyViewController: UIViewController, VerifyDisplayLogic
{
  var interactor: VerifyBusinessLogic?
  var router: (NSObjectProtocol & VerifyRoutingLogic & VerifyDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = VerifyInteractor()
    let presenter = VerifyPresenter()
    let router = VerifyRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  @IBOutlet weak var lblMobileNumber: UILabel!
    
  func doSomething()
  {
    let request = Verify.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Verify.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
//    lblMobileNumber.text = viewModel.LoginMobileNumber
  }
}

extension VerifyViewController {
    @IBAction func verifyAction() {
//        interactor?.verifySuccess(request: )
    }
    
}

